'use server';

import {
  GoogleGenerativeAI,
  HarmCategory,
  HarmBlockThreshold,
} from '@google/generative-ai';
import type {
  Supplier,
  PredictFailureRiskFactorsOutput,
  AnalyzeChartDataOutput,
  AnalyzeChartDataInput,
  AssetData,
} from '@/lib/types';

// === CONFIRME: ESTE É O MODELO CORRETO (2025+) ===
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY as string);

const model = genAI.getGenerativeModel({
  model: 'gemini-1.5-flash-latest', // <--- MODELO CORRIGIDO
  generationConfig: {
    temperature: 0.2,
    topP: 0.8,
    topK: 40,
    maxOutputTokens: 8192,
  },
  safetySettings: [
    { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_NONE },
    { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_NONE },
    { category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, threshold: HarmBlockThreshold.BLOCK_NONE },
    { category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_NONE },
  ],
});

// DEBUG: Confirme no console se o modelo está certo
console.log('MODEL USED:', model.model); // Deve logar: gemini-1.5-flash-latest

async function runAI<T>(prompt: string): Promise<T | { error: string }> {
  try {
    const result = await model.generateContent(prompt);
    
    if (
      !result.response ||
      !result.response.candidates ||
      result.response.candidates.length === 0
    ) {
      throw new Error('No content generated by AI.');
    }
    
    const responseText = result.response.text();
    if (!responseText) {
      throw new Error('AI returned an empty response.');
    }

    // Clean the response to ensure it's a valid JSON string
    const cleanedText = responseText.replace(/```json/g, '').replace(/```/g, '').trim();

    return JSON.parse(cleanedText) as T;

  } catch (error: any) {
    console.error('AI Error:', error.message);
    return { error: `AI generation failed. Details: ${error.message}` };
  }
}

export async function getRiskFactors(
  suppliers: Supplier[]
): Promise<PredictFailureRiskFactorsOutput | { error: string }> {
  if (suppliers.length === 0) {
    return {
      riskFactors: [],
      summary: 'Nenhum dado de equipamento disponível para analisar os fatores de risco.',
    };
  }
  const historicalData = suppliers
    .map(s => `Equipamento ${s.name} tempos de falha: ${s.failureTimes.join(', ')}`)
    .join('\n');

  const prompt = `Você é um engenheiro de confiabilidade especialista. Analise os seguintes dados históricos de falha para identificar os fatores de risco mais significativos que contribuem para as falhas.

Dados Históricos:
${historicalData}

Com base nestes dados, forneça um resumo técnico explicando o que os fatores de risco significam neste contexto e como o "percentual de importância" deve ser interpretado. Em seguida, liste os 3-5 principais fatores de risco classificados por importância. A importância deve ser um número entre 0 e 1, onde 1 indica o maior impacto no risco de falha. Se nenhum padrão claro emergir dos dados, retorne uma matriz vazia para "riskFactors".

Forneça a saída inteira em um único objeto JSON válido com a seguinte estrutura:
{
  "riskFactors": [ { "factor": "...", "importance": 0.0 } ],
  "summary": "..."
}
Não inclua nenhum texto ou formatação fora deste objeto JSON.`;

  return runAI<PredictFailureRiskFactorsOutput>(prompt);
}

export async function getChartAnalysis(
  input: AnalyzeChartDataInput
): Promise<AnalyzeChartDataOutput | { error: string }> {
  if (input.suppliers.length === 0) {
    return { error: 'Nenhum dado de equipamento para analisar.' };
  }

  const suppliersJson = JSON.stringify(input.suppliers.map(s => {
    const params: any = { name: s.name, distribution: s.distribution };
    if (s.distribution === 'Weibull') {
        params.beta = s.params.beta;
        params.eta = s.params.eta;
    } else if (s.distribution === 'Normal' || s.distribution === 'Lognormal') {
        params.mean = s.params.mean;
        params.stdDev = s.params.stdDev;
    } else if (s.distribution === 'Exponential') {
        params.lambda = s.params.lambda;
    }
    return params;
  }), null, 2);

  const prompt = `Você é um engenheiro de confiabilidade especialista. Sua tarefa é fornecer uma análise comparativa detalhada dos seguintes equipamentos com base em seus parâmetros de distribuição de probabilidade.

Dados dos Equipamentos:
${suppliersJson}

Analise os dados e gere uma explicação técnica detalhada para cada um dos quatro gráficos de confiabilidade a seguir. Para cada gráfico, compare os equipamentos e explique o que suas respectivas curvas significam, levando em consideração o tipo de distribuição de cada um. Use markdown para formatação, incluindo negrito para termos-chave e listas quando apropriado.

1.  **Curva de Confiabilidade R(t):** A probabilidade de um componente funcionar sem falha até o tempo t.
2.  **Probabilidade de Falha F(t):** A probabilidade de um componente falhar até o tempo t. Esta é a função de distribuição acumulada (FDA).
3.  **Densidade de Probabilidade f(t):** A probabilidade relativa de falha em um tempo específico t. Esta é a função de densidade de probabilidade (FDP).
4.  **Taxa de Falha λ(t) (Função de Risco):** A taxa instantânea de falha no tempo t, dado que o componente sobreviveu até t.

Forneça a saída inteira em um único objeto JSON válido com a seguinte estrutura:
{
  "reliability": { "title": "Curva de Confiabilidade - R(t)", "analysis": "..." },
  "failureProbability": { "title": "Probabilidade de Falha - F(t)", "analysis": "..." },
  "probabilityDensity": { "title": "Densidade de Probabilidade - f(t)", "analysis": "..." },
  "failureRate": { "title": "Taxa de Falha - λ(t)", "analysis": "..." }
}
Não inclua nenhum texto ou formatação fora deste objeto JSON.`;

  return runAI<AnalyzeChartDataOutput>(prompt);
}

export async function generateRcaReport(
  asset: AssetData,
  mtbf: number
): Promise<{ report: string } | { error: string }> {
    const maintGbvRatio = asset.gbv > 0 ? (asset.maintenanceCost / asset.gbv) * 100 : 0;
    
    const getModoDeFalha = () => {
        switch (asset.lifecycle) {
            case 'wearOut':
                return 'Desgaste (Beta > 1). As falhas estão se tornando mais frequentes com o tempo, indicando o fim da vida útil do componente. Ideal para manutenção preditiva.';
            case 'stable':
                return 'Falhas Aleatórias (Beta ≈ 1). As falhas ocorrem de forma imprevisível. A estratégia deve focar em minimizar o tempo de reparo (MTTR).';
            case 'infant':
                return 'Mortalidade Infantil (Beta < 1). Falhas prematuras, possivelmente devido a problemas de fabricação, instalação ou qualidade. A taxa de falha diminui com o tempo.';
            default:
                return 'Não determinado. A análise dos tempos de falha não foi conclusiva.';
        }
    };
    
    const getPosicaoCurvaBanheira = () => {
         switch (asset.lifecycle) {
            case 'wearOut':
                return `O ativo está claramente na fase de **Desgaste** da Curva da Banheira. A taxa de falhas é crescente, e a manutenção preventiva ou preditiva é crucial para evitar falhas catastróficas.`;
            case 'stable':
                return `O ativo está na fase de **Vida Útil** (ou falhas aleatórias). Nesta fase, a manutenção baseada no tempo tem menos eficácia. O foco deve ser na monitorização de condição e na rapidez da reparação.`;
            case 'infant':
                return `O ativo está na fase de **Mortalidade Infantil**. As falhas são prematuras. A estratégia deve ser focada na análise da causa raiz das falhas iniciais (qualidade, instalação, operação) em vez de manutenção preventiva por tempo.`;
            default:
                return 'A posição na curva não pôde ser determinada com precisão com os dados disponíveis.';
        }
    };

    const report = `### Relatório de Análise de Causa Raiz (RCA) - ${asset.name}

**1. Resumo Executivo:**
*   A análise dos indicadores de performance e confiabilidade para o ativo **${asset.name}** indica uma situação crítica. O alto impacto financeiro, combinado com um modo de falha característico de desgaste, reforça a recomendação de **substituição ou reforma imediata** para garantir a continuidade operacional e mitigar riscos financeiros e de segurança.

**2. Análise dos Indicadores de Falha:**
*   **Modo de Falha Predominante:** ${getModoDeFalha()}
*   **Saúde Preditiva (PdM Health):** O índice de saúde de **${asset.pdmHealth}%** é considerado baixo, sugerindo que as tecnologias de manutenção preditiva (como análise de vibração, termografia, etc.) estão detectando anomalias significativas e um estado de degradação avançado.
*   **Indicadores de Risco (RPN e Severidade):** O RPN (Número de Prioridade de Risco) de **${asset.rpn}** e a Severidade de **${asset.severity}** são elevados. Isso quantifica um alto risco para a operação, significando que uma falha neste ativo tem consequências graves, seja em termos de produção, segurança ou custos secundários.

**3. Análise de Impacto Financeiro:**
*   **Intensidade de Manutenção (Manut./GBV):** A intensidade de manutenção de **${maintGbvRatio.toFixed(2)}%** está acima do benchmark da indústria (tipicamente 2-3%), indicando que o custo para manter este ativo em operação é desproporcional ao seu valor contábil.
*   **Custo Total de Propriedade (TCO):** O Custo de Manutenção de **R$ ${asset.maintenanceCost.toLocaleString()}** somado à Perda por Downtime de **R$ ${asset.downtimeLoss.toLocaleString()}** revela um TCO elevado e insustentável, justificando o investimento em um ativo novo ou reformado.

**4. Análise da Curva da Banheira:**
*   ${getPosicaoCurvaBanheira()}

**5. Plano de Ação Recomendado:**
*   **Ação Imediata:** Iniciar o processo de **substituição ou reforma completa** do ativo. A decisão é fortemente suportada pelos indicadores de desgaste, alto risco (RPN) e impacto financeiro negativo (TCO).
*   **Ações de Mitigação (curto prazo):** Se a substituição não for imediata, aumentar a frequência de monitoramento preditivo e garantir que peças sobressalentes críticas estejam disponíveis em estoque para minimizar o MTTR em caso de falha.
*   **Ações de Melhoria Contínua (longo prazo):** Revisar o plano de manutenção para ativos similares, considerando a implementação de tarefas preditivas mais cedo no ciclo de vida. Analisar a possibilidade de um redesenho (redesign) se a falha for recorrente em ativos do mesmo tipo.
`;

    return { report };
}
